# frozen_string_literal: true

source "https://rubygems.org"

gem "aws-sdk-dynamodb"
gem "jwt"
gem "signet"
gem "twitter"

group :test, :development do
  gem "standard"
end

group :test do
  gem "rspec"
end
